---

- name: "Include setup tasks"
  include: tasks-initial.yml

- name: "Include config tasks"
  include: tasks-config.yml

- name: "Include teamcity distribution tasks"
  include: tasks-teamcity-distribution.yml

- name: "Include teamcity service tasks"
  include: tasks-teamcity-service.yml

- name: "Include mysql connector tasks"
  include: tasks-mysql-connector.yml

- name: "Include mysql db tasks"
  include: tasks-mysql-db.yml

- name: "Include vhosts apache2 tasks"
  include: tasks-vhosts-apache2.yml

- name: "Include vhosts nginx tasks"
  include: tasks-vhosts-nginx.yml