---

- name: "Setup | Update apt cache"
  become: yes
  become_user: "root"
  apt:
    update_cache: yes
    cache_valid_time: 86400

- name: "Setup | Install Dependencies"
  become: yes
  become_user: root
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - mysql-server
    - apache2
    - libapache2-mod-php5
    - php5
    - php5-mcrypt
    - phpmyadmin
    - mcrypt
    - nginx
    - python-mysqldb